name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trac_ik:$(date +%s)
      
    - name: Build package inside Docker container
      uses: docker://trac_ik:latest
      with:
        args: /bin/bash -c "mkdir build && cd build && cmake .. && make"
