name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t trac_ik:latest .
    
    # Build the package inside the Docker container
    - name: Build package inside Docker container
      run: docker run -v $(pwd):/src -w /src/build trac_ik:latest bash -c "cmake .. && make"
